name: Gomobile iOS

on:
  push:
    branches: [ master ]

jobs:
  gomobile-ios:
    name: Test Go
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v2
      - run: git fetch origin master

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Install gomobile
        run: go get golang.org/x/mobile/cmd/gomobile

      - name: Bind to iOS
        run: |
          ls /Users/runner
          ls /Users/runner/go
          ls /Users/runner/go/bin
          cd foogo
          /Users/runner/go/bin/gomobile bind --target ios -v
          ls -l
          echo "DONE :D" 