name: Master change

on:
  push:
    branches: [ master ]
    paths:
    - README.md

jobs:
    mustrun:
        name: Check changes
        runs-on: ubuntu-latest
        steps:
        - name: Check if must run
          run: echo "README.md has changed"